# What is the Y level that we should protect ores below?
protect-anything-below: 45
# Which blocks should we allow to be broken/placed under the specified y?
block-whitelist:
  - SHULKER_BOX
break-deny-message: 'You can''t break blocks here!'
place-deny-message: 'You can''t place blocks here!'