name: UnitedProtection
version: 1.2
main: org.unitedlands.protection.UnitedProtection
api-version: 1.18
depend: [ Towny ]
authors: [ Maroon28 ]
description: A plugin which protects the ores minable in the Earth world's caves on UnitedLands
website: unitedlands.org
